# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secure_connect_ruleset.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='secure_connect_ruleset.proto',
  package='secure_connect',
  syntax='proto2',
  serialized_pb=_b('\n\x1csecure_connect_ruleset.proto\x12\x0esecure_connect\"\x16\n\x06Target\x12\x0c\n\x04host\x18\x01 \x02(\t\"!\n\x04Rule\x12\r\n\x05regex\x18\x01 \x02(\t\x12\n\n\x02to\x18\x02 \x02(\t\"\x1c\n\tExclusion\x12\x0f\n\x07pattern\x18\x01 \x02(\t\"*\n\x0cSecureCookie\x12\x0c\n\x04host\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\"\xde\x01\n\x07RuleSet\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\'\n\x07targets\x18\x02 \x03(\x0b\x32\x16.secure_connect.Target\x12#\n\x05rules\x18\x03 \x03(\x0b\x32\x14.secure_connect.Rule\x12-\n\nexclusions\x18\x04 \x03(\x0b\x32\x19.secure_connect.Exclusion\x12\x33\n\rsecurecookies\x18\x05 \x03(\x0b\x32\x1c.secure_connect.SecureCookie\x12\x13\n\x0b\x64\x65\x66\x61ult_off\x18\x06 \x01(\t\"7\n\x0bRuleSetList\x12(\n\x07ruleset\x18\x01 \x03(\x0b\x32\x17.secure_connect.RuleSetB\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TARGET = _descriptor.Descriptor(
  name='Target',
  full_name='secure_connect.Target',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='secure_connect.Target.host', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=70,
)


_RULE = _descriptor.Descriptor(
  name='Rule',
  full_name='secure_connect.Rule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='regex', full_name='secure_connect.Rule.regex', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='secure_connect.Rule.to', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=105,
)


_EXCLUSION = _descriptor.Descriptor(
  name='Exclusion',
  full_name='secure_connect.Exclusion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pattern', full_name='secure_connect.Exclusion.pattern', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=135,
)


_SECURECOOKIE = _descriptor.Descriptor(
  name='SecureCookie',
  full_name='secure_connect.SecureCookie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='secure_connect.SecureCookie.host', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='secure_connect.SecureCookie.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=179,
)


_RULESET = _descriptor.Descriptor(
  name='RuleSet',
  full_name='secure_connect.RuleSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='secure_connect.RuleSet.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targets', full_name='secure_connect.RuleSet.targets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rules', full_name='secure_connect.RuleSet.rules', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exclusions', full_name='secure_connect.RuleSet.exclusions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='securecookies', full_name='secure_connect.RuleSet.securecookies', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_off', full_name='secure_connect.RuleSet.default_off', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=404,
)


_RULESETLIST = _descriptor.Descriptor(
  name='RuleSetList',
  full_name='secure_connect.RuleSetList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ruleset', full_name='secure_connect.RuleSetList.ruleset', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=461,
)

_RULESET.fields_by_name['targets'].message_type = _TARGET
_RULESET.fields_by_name['rules'].message_type = _RULE
_RULESET.fields_by_name['exclusions'].message_type = _EXCLUSION
_RULESET.fields_by_name['securecookies'].message_type = _SECURECOOKIE
_RULESETLIST.fields_by_name['ruleset'].message_type = _RULESET
DESCRIPTOR.message_types_by_name['Target'] = _TARGET
DESCRIPTOR.message_types_by_name['Rule'] = _RULE
DESCRIPTOR.message_types_by_name['Exclusion'] = _EXCLUSION
DESCRIPTOR.message_types_by_name['SecureCookie'] = _SECURECOOKIE
DESCRIPTOR.message_types_by_name['RuleSet'] = _RULESET
DESCRIPTOR.message_types_by_name['RuleSetList'] = _RULESETLIST

Target = _reflection.GeneratedProtocolMessageType('Target', (_message.Message,), dict(
  DESCRIPTOR = _TARGET,
  __module__ = 'secure_connect_ruleset_pb2'
  # @@protoc_insertion_point(class_scope:secure_connect.Target)
  ))
_sym_db.RegisterMessage(Target)

Rule = _reflection.GeneratedProtocolMessageType('Rule', (_message.Message,), dict(
  DESCRIPTOR = _RULE,
  __module__ = 'secure_connect_ruleset_pb2'
  # @@protoc_insertion_point(class_scope:secure_connect.Rule)
  ))
_sym_db.RegisterMessage(Rule)

Exclusion = _reflection.GeneratedProtocolMessageType('Exclusion', (_message.Message,), dict(
  DESCRIPTOR = _EXCLUSION,
  __module__ = 'secure_connect_ruleset_pb2'
  # @@protoc_insertion_point(class_scope:secure_connect.Exclusion)
  ))
_sym_db.RegisterMessage(Exclusion)

SecureCookie = _reflection.GeneratedProtocolMessageType('SecureCookie', (_message.Message,), dict(
  DESCRIPTOR = _SECURECOOKIE,
  __module__ = 'secure_connect_ruleset_pb2'
  # @@protoc_insertion_point(class_scope:secure_connect.SecureCookie)
  ))
_sym_db.RegisterMessage(SecureCookie)

RuleSet = _reflection.GeneratedProtocolMessageType('RuleSet', (_message.Message,), dict(
  DESCRIPTOR = _RULESET,
  __module__ = 'secure_connect_ruleset_pb2'
  # @@protoc_insertion_point(class_scope:secure_connect.RuleSet)
  ))
_sym_db.RegisterMessage(RuleSet)

RuleSetList = _reflection.GeneratedProtocolMessageType('RuleSetList', (_message.Message,), dict(
  DESCRIPTOR = _RULESETLIST,
  __module__ = 'secure_connect_ruleset_pb2'
  # @@protoc_insertion_point(class_scope:secure_connect.RuleSetList)
  ))
_sym_db.RegisterMessage(RuleSetList)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
